Repository Varbintech/next.varbintechcom, pull requests merged in 2023-05, with the labels that each got.

#81 79 add cookie popup 24.04.2023
  components-pages/layout/Layout.tsx
  components/common/buttons/Button.tsx
  components/common/cookie-popup/CookiePopup.stories.tsx
  components/common/cookie-popup/CookiePopup.tsx
  components/common/cookie-popup/styled-components.ts
  hooks/use-client-only-ref.ts
  package.json
  yarn.lock
Labels: GA

#85 add social behaviour
  components-pages/head/Head.tsx
  components-pages/head/HeadIndex.tsx
  components-pages/layout/Layout.tsx
  components/footer/Footer.tsx
  constants/meta.ts
  constants/settings.ts
  email-template/EmailTemplate.tsx
  pages/index.page.tsx
Labels: Index page

#86 add sentry with error page
  .gitignore
  components/common/link/NavigationLink.tsx
  mocks/navigation.ts
  next.config.js
  package.json
  pages/404.page.tsx
  pages/_app.page.tsx
  pages/_error.page.tsx
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  yarn.lock
Labels: Index page

#87 83 add sitemap 02.05.2023
  .gitignore
  components/common/link/NavigationLink.tsx
  next.config.js
  package.json
  tsconfig.json
  utils/generate-sitemap.js
  yarn.lock
Labels: Index page

#89 add description text for cookie link
  components/common/cookie-popup/CookiePopup.tsx
Labels: Index page, 🚨 lighthouse, SEO

#91 feat: add Twitter link
  mocks/social-icons.ts
Labels: enhancement, Index page, Promo

#95 Bugfix/light dark modes flash initial load
  hooks/use-mounted.ts
  pages/_app.page.tsx
  pages/_document.page.tsx
Labels: bug, enhancement
